name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Download Gradle (wrapper) hoặc dùng Gradle mặc định
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # 4. Build APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 5. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
